### ISSUE TITLE
TO DO: Figure out penalties

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#24]
Many penalties either aren't working or their purpose is unclear.

- [x] F_pen does not register a likelihood value yet should. What is going on.
- [x] Rave_pen is odd in that it penalized Rave values away from a user entered value. This does not seem to be appropriate. It is not Rdevs. It is not reported. Is it being used, and perhaps more importantly, should it be utilized. 
- [x] init_abund_pen is similar to Rave_pen. Is it being used, and more importantly, should it be used.

**Comment by brianlangseth-NOAA** [comment]
F_pen:
F_pen currently does not work. [In this line](https://github.com/brianlangseth-NOAA/Spatial-Workshop-SPASAM/blob/253c0d3df38e65efd13351157c4546b89d78c662/YFT_1area/Estimation_Model/YFT_1area.tpl#L4931), current_phase() registers the phase number and last_phase() is a true/false (1/0) thus current_phase() is NEVER less than last_phase() unless there is only 1 phase of estimation. Would need to set this as last_phase() == 0 to match intent of current code 

F_pen resets itself every phase. If I set the penalty to add a constant (F_pen_like+=1) then F_pen_like is 1 in the phase F is estimated. Once that phase is over, F_pen_like is reset to 0. Because F_pen isnt calculated in the last phase, F_pen_like is 0 and isn't technically added to the final objective function even though it contributes to the overall likelihood in the phase when estimating F. Thus I view it as a sort of psuedo_penalty only applied early.  

Rave_pen:
It is to penalize log-mean recruitment (LMR) from a specified starting value (Rave_mean). Penalty is turned on using Rave_pen_switch and weight of penalty is controlled by wt_Rave_pen. Note that this is different than parameterization for R0 which is set up by Rave_start, lb_R_ave, and ub_R_ave.  Effectively, Rave_pen is keeping R0 near its user-assigned value (Rave_mean), which is practice we would not know. 

Conclusion:
1. Need to correct penalties that have current_phase() < last_phase() to last_phase()==0 or just remove depending on answers to questions below. This applies for F_pen_like and multiple instances of M_pen_like.
2. Add Rave_pen value in the report out section. For our estimation, remove penalty from being applied (set wt_Rave_pen to 0 or Rave_pen_switch = 0)

Remaining questions for 
1. Do we report out the early penalty values used in the phase of estimation even though they become zero in the last phase? Alternatively, we can keep them present even in the last_phase (remove last_phase() == 0). That results in them being reported.

**Comment by JDeroba** [comment]
Brian,
As I recall, Dan coded the penalties only to apply to the early phases
because we were generally working in a simulation world where we knew what
the penalties should be and things ran/converged quicker when we had those
penalties but then let the model be free for the final phase. We're in a
pseudo-simulation world now and I think it is best to make decisions on
penalties as needed. In short, leave them as is for now (i.e., if used then
only applying early) mostly because fewer penalties seems like it should be
the default preference. If needed, then use the early penalties or include
them through the entire fitting process (during all phases) so that they
contribute to the final/total likelihood; but only as we find they are
necessary. I would say no need to report the penalty contributions during
early phases, but it doesn't really cost much if you want to make that
happen.

I've been working with the model for the last two days. Mostly I turned off
all devs, selectivities, etc., and I'm only estimating R-ave, init_abund,
and q parameters. My theory is that by estimating just the parameters
related to scale that: 1) the fit time is much less, which I have found to
be true, and 2) I can wrench with the scale parameters until I get close to
a sensible scale, and then free up other params and devs. I'm still
struggling with scale, especially as it pertains to R-ave and init_abund. I
still have several things I want to try and I will have more time this week
to keep playing. At the moment, I can't even seem to fix the init_abund at
a lower scale, and I'm not sure if something is really wrong, or if I'm
missing a switch. Anyway, more later.

JJD
