### ISSUE TITLE
Reporting data for the workshop

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [brianlangseth-NOAA/Spatial-Workshop-SPASAM#54]
Commit adb369a uploads (and commit a702c64 udpates) the script (Result Summary.R) to run for generating model reports to provide to the organizing committee. Their instructions for this are found at https://docs.google.com/document/d/1uE0DEi7V_xd8AD7kTMYePS_MWkoY_cTloo4uJff8DuQ/edit

Currently I have the single area (YFT_1area_7fleets_12) and spatial (YFT_2area_7fleets_F0.0001_update3) models outputted in the teamSPASAM_wkshp.rdata file. This sets up the framework, and should be fairly easy to run, however it is not final. There are a number of things that will need to be done. 

- [x] Update the current best case single area model with the one with a normal ALK assumption (or ignore that and just go with the lognormal for this preliminary run)
- [x] Update the current best case spatial model (if we get one that we like). Right now the one I have is the one with lognormal ALK. The one with normal ALK (YFT_2area_7fleets_F0.0001_13alk) is on github now, and could be used to compare to the one area model with normal ALK. My guess though is we may want to use the 2area/4fleet spatial model, in which case both the normal (YFT_2area_4fleets_F0.0001_13alk) and lognormal (YFT_2area_4fleets_F0.0001_update3) error ones are on github. 
- [x] Incorporate the 100 sim runs for the single area model into the output generation function. I did not have access to these files so did not do it. If this is done, the value for "teamSPASAM_pan_nsims" will need to be updated to 100 (right now its 1). 
- [x] Go through the Result Summary.R script and look over any lines that have comments starting with "CONFIRM" under them (because I wasn't entirely sure) or "TO DO" under them (because I didn't get to it or couldn't and these are things the organziers would like)

The instructions are not too clear. They say they want everything as a data frame, which is weird for single values. Right now I have longer entries either as vectors or matrices. They also say that the final output for after the workshop will have individual .rdata files for specific sims (e.g. teamXX_pan_runXXX_rep.rdata). I wasn't too clear on why they want the preliminary output all as one .rdata for all sims but final output in a different format. Thus, they may get back to us and want us to change things.

**Comment by JDeroba** [comment]
@brianlangseth-NOAA 

- updated the best single area model with the best normal ALK model ("YFT_1area_7fleets_14")
- used the 2 area 4 fleet model with a normal alk as the best spatial ("YFT_2area_4fleets_F0.0001_13alk"), at least for the workshop
- Incorporated the 100 1area runs, all of which used normal alk. Tried to get the dimensions as requested.
- Looked for the confirm and to do comments in the resultsummary script. I either confirmed or also wasn't sure. So is what it is.
- I learned the get function does not work well inside another function in R (all I could get were error messages). Basically the get function is not smart enough to look only within the outer functions memory environment. I ended up using dynGet, which is intended for use inside a function, but the help comes with warnings that it is experimental and should be used cautiously. I found no issues, however.
- I added features to the summaryResults function so that you can specify panmictic, spatial or both (as opposed to always requiring both as originally written). We'll need this feature at some point anyway, so now it's done.
